export const SEED_ACCOUNTS = [
  { id: 'a-chk', name: 'Chase Checking', type: 'checking', balance: 12425.41, asOf: '2026-04-13', external: false, annualRate: 0 },
  { id: 'a-sav', name: 'Savings', type: 'savings', balance: 6.71, asOf: '2026-04-13', external: false, annualRate: 0.045 },
  { id: 'a-401b', name: 'Boeing 401(k)', type: 'retirement', balance: 37967.41, asOf: '2026-04-13', external: false, annualRate: 0.08 },
  { id: 'a-roth', name: 'Roth IRA', type: 'retirement', balance: 4065.19, asOf: '2026-04-13', external: false, annualRate: 0.08 },
  { id: 'a-crypto', name: 'Crypto', type: 'crypto', balance: 25282.84, asOf: '2026-04-13', external: false, annualRate: 0 },
  { id: 'a-property', name: 'WeHo Condo (Market)', type: 'property', balance: 775500, asOf: '2026-04-13', external: false, annualRate: 0.02, acctGroup: 'weho-real-estate' },
  { id: 'a-mortgage', name: 'Mortgage (Doheny)', type: 'debt', balance: -629000, asOf: '2026-04-13', external: false, annualRate: 0.0325, zeroCap: true, linkedTo: 'a-property', acctGroup: 'weho-real-estate' },
  { id: 'a-chase-debt', name: 'Chase Freedom', type: 'debt', balance: -849.04, asOf: '2026-04-13', external: false, annualRate: 0.2299, zeroCap: true },
  { id: 'a-chase-prime', name: 'Chase Prime', type: 'debt', balance: -1229.42, asOf: '2026-04-13', external: false, annualRate: 0.2499, zeroCap: true },
  { id: 'a-discover-debt', name: 'Discover Card', type: 'debt', balance: -141.00, asOf: '2026-04-13', external: false, annualRate: 0.2449, zeroCap: true },
  { id: 'a-discover-loan', name: 'Discover Loan', type: 'debt', balance: 0, asOf: '2026-04-13', external: false, annualRate: 0.0899, zeroCap: true },
  { id: 'a-amex-debt', name: 'Amex', type: 'debt', balance: -589.49, asOf: '2026-04-13', external: false, annualRate: 0.2174, zeroCap: true },
  { id: 'a-tacoma', name: 'Tacoma Loan', type: 'debt', balance: 0, asOf: '2026-04-13', external: false, annualRate: 0.049, zeroCap: true },
  { id: 'a-rh-gold', name: 'Robinhood Gold', type: 'debt', balance: -12035.86, asOf: '2026-04-13', external: false, annualRate: 0.0575, zeroCap: true },
  { id: 'x-boeing', name: 'Boeing Payroll', type: 'income-source', balance: 0, asOf: '2026-04-13', external: true, annualRate: 0 },
  { id: 'x-diraq', name: 'Diraq Payroll', type: 'income-source', balance: 0, asOf: '2026-04-13', external: true, annualRate: 0 },
  { id: 'x-fedtax', name: 'Federal Tax', type: 'tax', balance: 0, asOf: '2026-04-13', external: true, annualRate: 0 },
  { id: 'x-statetax', name: 'State Tax', type: 'tax', balance: 0, asOf: '2026-04-13', external: true, annualRate: 0 },
  { id: 'x-fica', name: 'FICA', type: 'tax', balance: 0, asOf: '2026-04-13', external: true, annualRate: 0 },
  { id: 'x-benefits', name: 'Benefits', type: 'expense', balance: 0, asOf: '2026-04-13', external: true, annualRate: 0 },
  { id: 'x-escrow', name: 'Escrow / Prop Tax', type: 'expense', balance: 0, asOf: '2026-04-13', external: true, annualRate: 0 },
  { id: 'x-hoa', name: 'HOA', type: 'expense', balance: 0, asOf: '2026-04-13', external: true, annualRate: 0 },
  { id: 'x-insurance', name: 'Insurance', type: 'expense', balance: 0, asOf: '2026-04-13', external: true, annualRate: 0 },
  { id: 'x-util', name: 'Utilities', type: 'expense', balance: 0, asOf: '2026-04-13', external: true, annualRate: 0 },
  { id: 'x-subs', name: 'Subscriptions', type: 'expense', balance: 0, asOf: '2026-04-13', external: true, annualRate: 0 },
];

export const SEED_FLOWS = [
  { id: 'f-b1', name: 'Boeing Net Pay', from: 'x-boeing', to: 'a-chk', amount: 5138.13, period: '14', start: '2024-10-22', end: null, category: 'income', group: 'boeing', enabled: true },
  { id: 'f-b2', name: 'Boeing Federal Tax', from: 'x-boeing', to: 'x-fedtax', amount: 3200, period: '14', start: '2024-10-22', end: null, category: 'tax', group: 'boeing', enabled: true },
  { id: 'f-b3', name: 'Boeing State Tax', from: 'x-boeing', to: 'x-statetax', amount: 1400, period: '14', start: '2024-10-22', end: null, category: 'tax', group: 'boeing', enabled: true },
  { id: 'f-b4', name: 'Boeing FICA', from: 'x-boeing', to: 'x-fica', amount: 581, period: '14', start: '2024-10-22', end: null, category: 'tax', group: 'boeing', enabled: true },
  { id: 'f-b5', name: 'Boeing Benefits', from: 'x-boeing', to: 'x-benefits', amount: 214.12, period: '14', start: '2024-10-22', end: null, category: 'benefits', group: 'boeing', enabled: true },
  { id: 'f-b6', name: 'Boeing 401(k)', from: 'x-boeing', to: 'a-401b', amount: 0, period: '14', start: '2024-10-22', end: null, category: 'retirement-contrib', group: 'boeing', enabled: true },
  { id: 'f-d1', name: 'Diraq Net Pay', from: 'x-diraq', to: 'a-chk', amount: 4928.13, period: 'semi-monthly', start: '2026-05-15', end: null, category: 'income', group: 'diraq', enabled: true },
  { id: 'f-d2', name: 'Diraq Federal Tax', from: 'x-diraq', to: 'x-fedtax', amount: 2800, period: 'semi-monthly', start: '2026-05-15', end: null, category: 'tax', group: 'diraq', enabled: true },
  { id: 'f-d3', name: 'Diraq State Tax', from: 'x-diraq', to: 'x-statetax', amount: 420, period: 'semi-monthly', start: '2026-05-15', end: null, category: 'tax', group: 'diraq', enabled: true },
  { id: 'f-d4', name: 'Diraq FICA', from: 'x-diraq', to: 'x-fica', amount: 530, period: 'semi-monthly', start: '2026-05-15', end: null, category: 'tax', group: 'diraq', enabled: true },
  { id: 'f-d5', name: 'Diraq Benefits', from: 'x-diraq', to: 'x-benefits', amount: 214.12, period: 'semi-monthly', start: '2026-05-15', end: null, category: 'benefits', group: 'diraq', enabled: true },
  { id: 'f-d6', name: 'Diraq 401(k)', from: 'x-diraq', to: 'a-401b', amount: 0, period: 'semi-monthly', start: '2026-05-15', end: null, category: 'retirement-contrib', group: 'diraq', enabled: true },
  { id: 'f-m1', name: 'Mortgage P&I', from: 'a-chk', to: 'a-mortgage', amount: 2976.81, period: 'monthly', start: '2022-08-01', end: null, category: 'housing', group: 'mortgage', enabled: true },
  { id: 'f-m3', name: 'Escrow / Prop Tax', from: 'a-chk', to: 'x-escrow', amount: 808.75, period: 'monthly', start: '2022-08-01', end: null, category: 'housing', group: 'mortgage', enabled: true },
  { id: 'f-m4', name: 'HOA', from: 'a-chk', to: 'x-hoa', amount: 517, period: 'monthly', start: '2022-08-01', end: null, category: 'housing', group: 'mortgage', enabled: true },
  { id: 'f-2', name: 'Tacoma Payment', from: 'a-chk', to: 'a-tacoma', amount: 856.83, period: 'monthly', start: '2025-05-06', end: '2031-05-06', category: 'auto', group: null, enabled: true },
  { id: 'f-3', name: 'Auto Insurance', from: 'a-chk', to: 'x-insurance', amount: 388.94, period: 'monthly', start: '2022-09-08', end: null, category: 'insurance', group: null, enabled: true },
  { id: 'f-4', name: 'Home Insurance', from: 'a-chk', to: 'x-insurance', amount: 108.25, period: 'monthly', start: '2022-09-10', end: null, category: 'insurance', group: null, enabled: true },
  { id: 'f-5', name: 'Discover Card Payment', from: 'a-chk', to: 'a-discover-debt', amount: 227, period: 'monthly', start: '2024-05-06', end: null, category: 'debt', group: null, enabled: true },
  { id: 'f-6', name: 'Discover Loan Payment', from: 'a-chk', to: 'a-discover-loan', amount: 234.02, period: 'monthly', start: '2024-11-07', end: null, category: 'debt', group: null, enabled: true },
  { id: 'f-7', name: 'Citi Card Payment', from: 'a-chk', to: 'a-amex-debt', amount: 302.65, period: 'monthly', start: '2024-04-23', end: null, category: 'debt', group: null, enabled: true },
  { id: 'f-8', name: 'Chase Card Payment', from: 'a-chk', to: 'a-chase-debt', amount: 574.61, period: 'monthly', start: '2022-09-26', end: null, category: 'debt', group: null, enabled: true },
  { id: 'f-9', name: 'Phone Bill', from: 'a-chk', to: 'x-util', amount: 145.63, period: 'monthly', start: '2024-03-28', end: null, category: 'utility', group: null, enabled: true },
  { id: 'f-10', name: 'Spotify', from: 'a-chk', to: 'x-subs', amount: 11.99, period: 'monthly', start: '2022-08-25', end: null, category: 'subscription', group: null, enabled: true },
  { id: 'f-11', name: 'Proton', from: 'a-chk', to: 'x-subs', amount: 11.99, period: 'monthly', start: '2022-08-25', end: null, category: 'subscription', group: null, enabled: true },
];
